image: alpine

before_script:
  - 'which ssh-agent || ( apk add openssh-client yarn )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "preview.altab.io" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'

stages:
  - deploy

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - ssh debian@preview.altab.io -p 22 "export NVM_DIR="\$HOME/.nvm" ; \. "\$NVM_DIR/nvm.sh" ; [ -s "\$NVM_DIR/bash_completion" ] ; \. "\$NVM_DIR/bash_completion" ; cd nuxt3-tailwind-template ; git config pull.rebase false ; git checkout develop ; git reset --hard develop ; git pull ; yarn ; yarn build-staging ; yarn start-pm2-staging; pm2 save ; exit"
    - echo "Deploy to staging server finished"
  environment:
    name: staging
    url: http://altab.io:3000
  only:
    - develop
# deploy_prod:
#   stage: deploy
#   script:
#     - echo "Deploy to production server"
#     - ssh debian@preview.altab.io -p 22 "export NVM_DIR="\$HOME/.nvm" ; \. "\$NVM_DIR/nvm.sh" ; [ -s "\$NVM_DIR/bash_completion" ] ; \. "\$NVM_DIR/bash_completion" ; cd nuxt3-tailwind-template/prod ; git config pull.rebase false ; git checkout master ; git reset --hard master ; git pull ; yarn ; yarn build-prod ; yarn start-pm2-prod; pm2 save ; exit"
#     - echo "Deploy to production server finished"
#   environment:
#     name: production
#     url: http://altab.io:XXXX
#   when: manual
#   only:
#     - master
